### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'document')

### ISSUE THREAD

**Issue by rishabkumar7** [Hashnode/starter-kit#77]
**Version of Node.js:**
21.5.0

**pnpm version**
8.14.1

**Operating System**
Windows 11

**Issue**
When running `pnpm dev` after `pnpm install` in the `/personal` theme, I am getting this error:
Console:
```
[next] TypeError: Cannot read properties of undefined (reading 'document')
[next]     at parseRequestExtendedArgs (E:\GitHub\starter-kit\node_modules\.pnpm\graphql-request@6.1.0_graphql@16.8.1\node_modules\graphql-request\build\cjs\parseArgs.js:38:25)
[next]     at request (E:\GitHub\starter-kit\node_modules\.pnpm\graphql-request@6.1.0_graphql@16.8.1\node_modules\graphql-request\build\cjs\index.js:330:72)
[next]     at getRedirectionRules (E:\GitHub\starter-kit\packages\blog-starter-kit\themes\personal\next.config.js:31:21)
[next]     at Object.redirects (E:\GitHub\starter-kit\packages\blog-starter-kit\themes\personal\next.config.js:92:16)
[next]     at loadRedirects (E:\GitHub\starter-kit\node_modules\.pnpm\next@13.5.5_react-dom@18.2.0_react@18.2.0\node_modules\next\dist\lib\load-custom-routes.js:360:34)
[next]     at loadCustomRoutes (E:\GitHub\starter-kit\node_modules\.pnpm\next@13.5.5_react-dom@18.2.0_react@18.2.0\node_modules\next\dist\lib\load-custom-routes.js:438:9)
[next]     at setupFsCheck (E:\GitHub\starter-kit\node_modules\.pnpm\next@13.5.5_react-dom@18.2.0_react@18.2.0\node_modules\next\dist\server\lib\router-utils\filesystem.js:235:60)
[next]     at initialize (E:\GitHub\starter-kit\node_modules\.pnpm\next@13.5.5_react-dom@18.2.0_react@18.2.0\node_modules\next\dist\server\lib\router-server.js:56:58)
[next]     at async Server.<anonymous> (E:\GitHub\starter-kit\node_modules\.pnpm\next@13.5.5_react-dom@18.2.0_react@18.2.0\node_modules\next\dist\server\lib\start-server.js:221:36)
```

Browser:
```
TypeError: The "path" argument must be of type string. Received undefined
    at Object.join (node:path:433:7)
    at noopServiceWorkerMiddleware (D:\Downloads\status\node_modules\react-dev-utils\noopServiceWorkerMiddleware.js:14:26)
    at Layer.handle [as handle_request] (D:\Downloads\status\node_modules\express\lib\router\layer.js:95:5)
    at trim_prefix (D:\Downloads\status\node_modules\express\lib\router\index.js:328:13)
    at D:\Downloads\status\node_modules\express\lib\router\index.js:286:9
    at Function.process_params (D:\Downloads\status\node_modules\express\lib\router\index.js:346:12)
    at next (D:\Downloads\status\node_modules\express\lib\router\index.js:280:10)
    at launchEditorMiddleware (D:\Downloads\status\node_modules\react-dev-utils\errorOverlayMiddleware.js:20:7)
    at Layer.handle [as handle_request] (D:\Downloads\status\node_modules\express\lib\router\layer.js:95:5)
    at trim_prefix (D:\Downloads\status\node_modules\express\lib\router\index.js:328:13)
    at D:\Downloads\status\node_modules\express\lib\router\index.js:286:9
    at Function.process_params (D:\Downloads\status\node_modules\express\lib\router\index.js:346:12)
    at next (D:\Downloads\status\node_modules\express\lib\router\index.js:280:10)
    at handleWebpackInternalMiddleware (D:\Downloads\status\node_modules\react-dev-utils\evalSourceMapMiddleware.js:42:7)
    at Layer.handle [as handle_request] (D:\Downloads\status\node_modules\express\lib\router\layer.js:95:5)
    at trim_prefix (D:\Downloads\status\node_modules\express\lib\router\index.js:328:13)
    at D:\Downloads\status\node_modules\express\lib\router\index.js:286:9
    at Function.process_params (D:\Downloads\status\node_modules\express\lib\router\index.js:346:12)
    at next (D:\Downloads\status\node_modules\express\lib\router\index.js:280:10)
    at compression (D:\Downloads\status\node_modules\compression\index.js:220:5)
    at Layer.handle [as handle_request] (D:\Downloads\status\node_modules\express\lib\router\layer.js:95:5)
    at trim_prefix (D:\Downloads\status\node_modules\express\lib\router\index.js:328:13)
    at D:\Downloads\status\node_modules\express\lib\router\index.js:286:9
    at Function.process_params (D:\Downloads\status\node_modules\express\lib\router\index.js:346:12)
    at next (D:\Downloads\status\node_modules\express\lib\router\index.js:280:10)
    at next (D:\Downloads\status\node_modules\express\lib\router\route.js:136:14)
    at next (D:\Downloads\status\node_modules\express\lib\router\route.js:140:7)
    at next (D:\Downloads\status\node_modules\express\lib\router\route.js:140:7)
    at next (D:\Downloads\status\node_modules\express\lib\router\route.js:140:7)
    at next (D:\Downloads\status\node_modules\express\lib\router\route.js:140:7)
    at next (D:\Downloads\status\node_modules\express\lib\router\route.js:140:7)
    at next (D:\Downloads\status\node_modules\express\lib\router\route.js:140:7)
    at next (D:\Downloads\status\node_modules\express\lib\router\route.js:140:7)
    at next (D:\Downloads\status\node_modules\express\lib\router\route.js:140:7)
    at next (D:\Downloads\status\node_modules\express\lib\router\route.js:140:7)
    at next (D:\Downloads\status\node_modules\express\lib\router\route.js:140:7)
    at next (D:\Downloads\status\node_modules\express\lib\router\route.js:140:7)
    at next (D:\Downloads\status\node_modules\express\lib\router\route.js:140:7)
    at next (D:\Downloads\status\node_modules\express\lib\router\route.js:140:7)
    at next (D:\Downloads\status\node_modules\express\lib\router\route.js:140:7)
    at next (D:\Downloads\status\node_modules\express\lib\router\route.js:140:7)
    at next (D:\Downloads\status\node_modules\express\lib\router\route.js:140:7)
    at next (D:\Downloads\status\node_modules\express\lib\router\route.js:140:7)
    at next (D:\Downloads\status\node_modules\express\lib\router\route.js:140:7)
    at next (D:\Downloads\status\node_modules\express\lib\router\route.js:140:7)
    at next (D:\Downloads\status\node_modules\express\lib\router\route.js:140:7)
    at next (D:\Downloads\status\node_modules\express\lib\router\route.js:140:7)
    at next (D:\Downloads\status\node_modules\express\lib\router\route.js:140:7)
    at next (D:\Downloads\status\node_modules\express\lib\router\route.js:140:7)
    at next (D:\Downloads\status\node_modules\express\lib\router\route.js:140:7)
```

**Comment by mixed-signal** [comment]
I'm seeing the same error while trying to run locally.

**Comment by ashudevcodes** [comment]
Check that the file name is `.env.local`, not `.env.example`. This should resolve the error, as it was caused by the process.env not reading the environment variable

![image](https://github.com/Hashnode/starter-kit/assets/105356967/093a1091-a99e-419f-8ac9-4948a0849dc2)

**Comment by rishabkumar7** [comment]
Thanks, missed that step. It works ✅
